
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:

  # Database for user profiles
  MatchobUsersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: MatchobUsers
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH

  # Cognito User Pool
  MatchobUserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: matchob-dev-users
      UsernameAttributes:
        - email
      AutoVerifiedAttributes:
        - email
      Policies:
        PasswordPolicy:
          MinimumLength: 12

  # Frontend application client
  MatchobUserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId: !Ref MatchobUserPool
      ClientName: matchob-frontend
      GenerateSecret: false
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthFlows:
        - code
      AllowedOAuthScopes:
        - openid
        - email
        - profile
      CallbackURLs:
        - http://localhost:3000/auth/callback
      LogoutURLs:
        - http://localhost:3000/
      SupportedIdentityProviders:
        - COGNITO

  # API Gateway with Cognito authorization
  MatchobApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: dev
      Auth:
        DefaultAuthorizer: CognitoAuthorizer
        Authorizers:
          CognitoAuthorizer:
            UserPoolArn: !GetAtt MatchobUserPool.Arn

  # Lambda for GET /profile
  GetProfileFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get-profile/
      Handler: app.lambda_handler
      Runtime: python3.13
      Timeout: 10

      Environment:
        Variables:
          USERS_TABLE: !Ref MatchobUsersTable
          DYNAMODB_ENDPOINT: ""

      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref MatchobUsersTable

      Events:
        GetProfile:
          Type: Api
          Properties:
            RestApiId: !Ref MatchobApi
            Path: /profile
            Method: get
  MatchobUserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      Domain: matchob-dev-backend
      UserPoolId: !Ref MatchobUserPool
Outputs:
  UserPoolId:
    Value: !Ref MatchobUserPool

  UserPoolClientId:
    Value: !Ref MatchobUserPoolClient

  ApiUrl:
    Value: !Sub "https://${MatchobApi}.execute-api.${AWS::Region}.amazonaws.com/dev/profile"
